---
title: "School of Geography PGR Conference 2024"
---

Welcome to the School of Geography PGR Conference at the University of Leeds. The conference will take place on the **5th November 2024**, and is open to all **PGRs** and **academic staff** here at the School of Geography!

The PGR conference has been a longstanding event within the School of Geography to showcase the exiciting and important research from postgraduates. The conference provides an opportunity for postgraduates to present ongoing research, network with peers and develop new insights in a friendly and constructive setting. It is hoped that all postgraduates from across the School of Geography attend, whether presenting a talk, providing a poster, or coming along and engaging with your peers.

The School of Geography PGR conference will include:

-   **10-min** presentations from postgraduates followed by **5-min** Q&A
-   Poster session & networking opportunity
-   Career Sessions
-   Lunch & social

To present a research talk or a poster, more details are provided [here](Presentation.qmd).

Lunch will be provided - however please **bring your own water bottle + mug** for refreshments!

### Key Dates

-   ~~Deadline for presentation: 11th October 2024.~~
-   ~~Deadline for poster: 11th October 2024.~~
-   ~~**Send presentation to gy17pls\@leeds.ac.uk by 1st November 2024**~~
-   SoG PGR Conference: 5th November 2024.

### Online Teams Links

[Seminar room 1](https://teams.microsoft.com/l/meetup-join/19%3ameeting_OWE2YWQ0MjctM2UyMS00M2RlLTljZTktZjBhNjdhMDdiODQ1%40thread.v2/0?context=%7b%22Tid%22%3a%22bdeaeda8-c81d-45ce-863e-5232a535b7cb%22%2c%22Oid%22%3a%22e00978be-e503-49b1-931a-507f7901b187%22%7d)

[Seminar room 2](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NThmNGVkNTMtZGFjZC00Nzc1LWIwYWEtODU4ZTc1ZWE3ZDdk%40thread.v2/0?context=%7b%22Tid%22%3a%22bdeaeda8-c81d-45ce-863e-5232a535b7cb%22%2c%22Oid%22%3a%22e00978be-e503-49b1-931a-507f7901b187%22%7d)
